name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: rust:latest
      options: --user root
    steps:
    - uses: actions/checkout@v3
    - name: install-deps
      run: apt install clang -y
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run:   cargo test -- --verbose
